name: pull

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - release/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  linux-xenial-py3_7-gcc5_4-build:
    name: linux-xenial-py3.7-gcc5.4
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-xenial-py3.7-gcc5.4
      docker-image-name: pytorch-linux-xenial-py3.7-gcc5.4

  linux-xenial-py3_7-gcc5_4-test:
    name: linux-xenial-py3.7-gcc5.4
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-xenial-py3_7-gcc5_4-build
    with:
      build-environment: linux-xenial-py3.7-gcc5.4
      docker-image: ${{ needs.linux-xenial-py3_7-gcc5_4-build.outputs.docker-image }}
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 1, runner: "linux.2xlarge" },

          { config: "default", shard: 1, num_shards: 2, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 2, runner: "linux.2xlarge" },

          { config: "default", shard: 1, num_shards: 3, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 3, runner: "linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 3, runner: "linux.2xlarge" },

          { config: "default", shard: 1, num_shards: 4, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 4, runner: "linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 4, runner: "linux.2xlarge" },
          { config: "default", shard: 4, num_shards: 4, runner: "linux.2xlarge" },

          { config: "default", shard: 1, num_shards: 5, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 5, runner: "linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 5, runner: "linux.2xlarge" },
          { config: "default", shard: 4, num_shards: 5, runner: "linux.2xlarge" },
          { config: "default", shard: 5, num_shards: 5, runner: "linux.2xlarge" },

          { config: "distributed", shard: 1, num_shards: 1, runner: "linux.2xlarge" },

          { config: "distributed", shard: 1, num_shards: 2, runner: "linux.2xlarge" },
          { config: "distributed", shard: 2, num_shards: 2, runner: "linux.2xlarge" },

          { config: "distributed", shard: 1, num_shards: 3, runner: "linux.2xlarge" },
          { config: "distributed", shard: 2, num_shards: 3, runner: "linux.2xlarge" },
          { config: "distributed", shard: 3, num_shards: 3, runner: "linux.2xlarge" },

          { config: "distributed", shard: 1, num_shards: 4, runner: "linux.2xlarge" },
          { config: "distributed", shard: 2, num_shards: 4, runner: "linux.2xlarge" },
          { config: "distributed", shard: 3, num_shards: 4, runner: "linux.2xlarge" },
          { config: "distributed", shard: 4, num_shards: 4, runner: "linux.2xlarge" },

          { config: "distributed", shard: 1, num_shards: 5, runner: "linux.2xlarge" },
          { config: "distributed", shard: 2, num_shards: 5, runner: "linux.2xlarge" },
          { config: "distributed", shard: 3, num_shards: 5, runner: "linux.2xlarge" },
          { config: "distributed", shard: 4, num_shards: 5, runner: "linux.2xlarge" },
          { config: "distributed", shard: 5, num_shards: 5, runner: "linux.2xlarge" },

          { config: "docs_test", shard: 1, num_shards: 1,  runner: "linux.2xlarge" },
          { config: "backwards_compat", shard: 1, num_shards: 1, runner: "linux.2xlarge" },
          { config: "jit_legacy", shard: 1, num_shards: 1, runner: "linux.2xlarge" },
        ]}

  linux-xenial-py3_7-gcc7-build:
    name: linux-xenial-py3.7-gcc7
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-xenial-py3.7-gcc7
      docker-image-name: pytorch-linux-xenial-py3.7-gcc7

  linux-xenial-py3_7-gcc7-test:
    name: linux-xenial-py3.7-gcc7
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-xenial-py3_7-gcc7-build
    with:
      build-environment: linux-xenial-py3.7-gcc7
      docker-image: ${{ needs.linux-xenial-py3_7-gcc7-build.outputs.docker-image }}
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 1, runner: "linux.2xlarge" },

          { config: "default", shard: 1, num_shards: 2, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 2, runner: "linux.2xlarge" },

          { config: "default", shard: 1, num_shards: 3, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 3, runner: "linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 3, runner: "linux.2xlarge" },

          { config: "default", shard: 1, num_shards: 4, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 4, runner: "linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 4, runner: "linux.2xlarge" },
          { config: "default", shard: 4, num_shards: 4, runner: "linux.2xlarge" },

          { config: "default", shard: 1, num_shards: 5, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 5, runner: "linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 5, runner: "linux.2xlarge" },
          { config: "default", shard: 4, num_shards: 5, runner: "linux.2xlarge" },
          { config: "default", shard: 5, num_shards: 5, runner: "linux.2xlarge" },
        ]}

  linux-xenial-py3_7-clang7-asan-build:
    name: linux-xenial-py3.7-clang7-asan
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-xenial-py3.7-clang7-asan
      docker-image-name: pytorch-linux-xenial-py3-clang7-asan

  linux-xenial-py3_7-clang7-asan-test:
    name: linux-xenial-py3.7-clang7-asan
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-xenial-py3_7-clang7-asan-build
    with:
      build-environment: linux-xenial-py3.7-clang7-asan
      docker-image: ${{ needs.linux-xenial-py3_7-clang7-asan-build.outputs.docker-image }}
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 1, runner: "linux.2xlarge" },

          { config: "default", shard: 1, num_shards: 2, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 2, runner: "linux.2xlarge" },

          { config: "default", shard: 1, num_shards: 3, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 3, runner: "linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 3, runner: "linux.2xlarge" },

          { config: "default", shard: 1, num_shards: 4, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 4, runner: "linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 4, runner: "linux.2xlarge" },
          { config: "default", shard: 4, num_shards: 4, runner: "linux.2xlarge" },

          { config: "default", shard: 1, num_shards: 5, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 5, runner: "linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 5, runner: "linux.2xlarge" },
          { config: "default", shard: 4, num_shards: 5, runner: "linux.2xlarge" },
          { config: "default", shard: 5, num_shards: 5, runner: "linux.2xlarge" },
        ]}

  linux-bionic-py3_7-clang9-build:
    name: linux-bionic-py3.7-clang9
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-bionic-py3.7-clang9
      docker-image-name: pytorch-linux-bionic-py3.7-clang9

  linux-bionic-py3_7-clang9-test:
    name: linux-bionic-py3.7-clang9
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-bionic-py3_7-clang9-build
    with:
      build-environment: linux-bionic-py3.7-clang9
      docker-image: ${{ needs.linux-bionic-py3_7-clang9-build.outputs.docker-image }}
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 1, runner: "linux.2xlarge" },

          { config: "default", shard: 1, num_shards: 2, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 2, runner: "linux.2xlarge" },

          { config: "default", shard: 1, num_shards: 3, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 3, runner: "linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 3, runner: "linux.2xlarge" },

          { config: "default", shard: 1, num_shards: 4, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 4, runner: "linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 4, runner: "linux.2xlarge" },
          { config: "default", shard: 4, num_shards: 4, runner: "linux.2xlarge" },

          { config: "default", shard: 1, num_shards: 5, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 5, runner: "linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 5, runner: "linux.2xlarge" },
          { config: "default", shard: 4, num_shards: 5, runner: "linux.2xlarge" },
          { config: "default", shard: 5, num_shards: 5, runner: "linux.2xlarge" },

          { config: "crossref", shard: 1, num_shards: 1, runner: "linux.2xlarge" },

          { config: "crossref", shard: 1, num_shards: 2, runner: "linux.2xlarge" },
          { config: "crossref", shard: 2, num_shards: 2, runner: "linux.2xlarge" },

          { config: "crossref", shard: 1, num_shards: 3, runner: "linux.2xlarge" },
          { config: "crossref", shard: 2, num_shards: 3, runner: "linux.2xlarge" },
          { config: "crossref", shard: 3, num_shards: 3, runner: "linux.2xlarge" },

          { config: "crossref", shard: 1, num_shards: 4, runner: "linux.2xlarge" },
          { config: "crossref", shard: 2, num_shards: 4, runner: "linux.2xlarge" },
          { config: "crossref", shard: 3, num_shards: 4, runner: "linux.2xlarge" },
          { config: "crossref", shard: 4, num_shards: 4, runner: "linux.2xlarge" },

          { config: "crossref", shard: 1, num_shards: 5, runner: "linux.2xlarge" },
          { config: "crossref", shard: 2, num_shards: 5, runner: "linux.2xlarge" },
          { config: "crossref", shard: 3, num_shards: 5, runner: "linux.2xlarge" },
          { config: "crossref", shard: 4, num_shards: 5, runner: "linux.2xlarge" },
          { config: "crossref", shard: 5, num_shards: 5, runner: "linux.2xlarge" },
        ]}

  linux-xenial-cuda11_3-py3_7-gcc7-build:
    name: linux-xenial-cuda11.3-py3.7-gcc7
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-xenial-cuda11.3-py3.7-gcc7
      docker-image-name: pytorch-linux-xenial-cuda11.3-cudnn8-py3-gcc7

  linux-xenial-cuda11_3-py3_7-gcc7-test:
    name: linux-xenial-cuda11.3-py3.7-gcc7
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-xenial-cuda11_3-py3_7-gcc7-build
    with:
      build-environment: linux-xenial-cuda11.3-py3.7-gcc7
      docker-image: ${{ needs.linux-xenial-cuda11_3-py3_7-gcc7-build.outputs.docker-image }}
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 1, runner: "linux.4xlarge.nvidia.gpu" },

          { config: "default", shard: 1, num_shards: 2, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 2, num_shards: 2, runner: "linux.4xlarge.nvidia.gpu" },

          { config: "default", shard: 1, num_shards: 3, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 2, num_shards: 3, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 3, num_shards: 3, runner: "linux.4xlarge.nvidia.gpu" },

          { config: "default", shard: 1, num_shards: 4, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 2, num_shards: 4, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 3, num_shards: 4, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 4, num_shards: 4, runner: "linux.4xlarge.nvidia.gpu" },

          { config: "default", shard: 1, num_shards: 5, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 2, num_shards: 5, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 3, num_shards: 5, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 4, num_shards: 5, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 5, num_shards: 5, runner: "linux.4xlarge.nvidia.gpu" },

          { config: "distributed", shard: 1, num_shards: 1, runner: "linux.8xlarge.nvidia.gpu" },

          { config: "distributed", shard: 1, num_shards: 2, runner: "linux.8xlarge.nvidia.gpu" },
          { config: "distributed", shard: 2, num_shards: 2, runner: "linux.8xlarge.nvidia.gpu" },

          { config: "distributed", shard: 1, num_shards: 3, runner: "linux.8xlarge.nvidia.gpu" },
          { config: "distributed", shard: 2, num_shards: 3, runner: "linux.8xlarge.nvidia.gpu" },
          { config: "distributed", shard: 3, num_shards: 3, runner: "linux.8xlarge.nvidia.gpu" },

          { config: "distributed", shard: 1, num_shards: 4, runner: "linux.8xlarge.nvidia.gpu" },
          { config: "distributed", shard: 2, num_shards: 4, runner: "linux.8xlarge.nvidia.gpu" },
          { config: "distributed", shard: 3, num_shards: 4, runner: "linux.8xlarge.nvidia.gpu" },
          { config: "distributed", shard: 4, num_shards: 4, runner: "linux.8xlarge.nvidia.gpu" },

          { config: "distributed", shard: 1, num_shards: 5, runner: "linux.8xlarge.nvidia.gpu" },
          { config: "distributed", shard: 2, num_shards: 5, runner: "linux.8xlarge.nvidia.gpu" },
          { config: "distributed", shard: 3, num_shards: 5, runner: "linux.8xlarge.nvidia.gpu" },
          { config: "distributed", shard: 4, num_shards: 5, runner: "linux.8xlarge.nvidia.gpu" },
          { config: "distributed", shard: 5, num_shards: 5, runner: "linux.8xlarge.nvidia.gpu" },

        ]}

  linux-bionic-rocm5_1-py3_7-build:
    name: linux-bionic-rocm5.1-py3.7
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-bionic-rocm5.1-py3.7
      docker-image-name: pytorch-linux-bionic-rocm5.1-py3.7

  linux-bionic-rocm5_1-py3_7-test:
    name: linux-bionic-rocm5.1-py3.7
    uses: ./.github/workflows/_rocm-test.yml
    needs: linux-bionic-rocm5_1-py3_7-build
    with:
      build-environment: linux-bionic-rocm5.1-py3.7
      docker-image: ${{ needs.linux-bionic-rocm5_1-py3_7-build.outputs.docker-image }}
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 1, runner: "linux.rocm.gpu" },

          { config: "default", shard: 1, num_shards: 2, runner: "linux.rocm.gpu" },
          { config: "default", shard: 2, num_shards: 2, runner: "linux.rocm.gpu" },

          { config: "default", shard: 1, num_shards: 3, runner: "linux.rocm.gpu" },
          { config: "default", shard: 2, num_shards: 3, runner: "linux.rocm.gpu" },
          { config: "default", shard: 3, num_shards: 3, runner: "linux.rocm.gpu" },

          { config: "default", shard: 1, num_shards: 4, runner: "linux.rocm.gpu" },
          { config: "default", shard: 2, num_shards: 4, runner: "linux.rocm.gpu" },
          { config: "default", shard: 3, num_shards: 4, runner: "linux.rocm.gpu" },
          { config: "default", shard: 4, num_shards: 4, runner: "linux.rocm.gpu" },

          { config: "default", shard: 1, num_shards: 5, runner: "linux.rocm.gpu" },
          { config: "default", shard: 2, num_shards: 5, runner: "linux.rocm.gpu" },
          { config: "default", shard: 3, num_shards: 5, runner: "linux.rocm.gpu" },
          { config: "default", shard: 4, num_shards: 5, runner: "linux.rocm.gpu" },
          { config: "default", shard: 5, num_shards: 5, runner: "linux.rocm.gpu" },
        ]}
    secrets:
      AWS_OSSCI_METRICS_V2_ACCESS_KEY_ID: ${{ secrets.AWS_OSSCI_METRICS_V2_ACCESS_KEY_ID }}
      AWS_OSSCI_METRICS_V2_SECRET_ACCESS_KEY: ${{ secrets.AWS_OSSCI_METRICS_V2_SECRET_ACCESS_KEY }}

  pytorch-xla-linux-bionic-py3_7-clang8-build:
    name: pytorch-xla-linux-bionic-py3.7-clang8
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: pytorch-xla-linux-bionic-py3.7-clang8
      docker-image-name: xla_base

  pytorch-xla-linux-bionic-py3_7-clang8-test:
    name: pytorch-xla-linux-bionic-py3.7-clang8
    uses: ./.github/workflows/_linux-test.yml
    needs: pytorch-xla-linux-bionic-py3_7-clang8-build
    with:
      build-environment: pytorch-xla-linux-bionic-py3.7-clang8
      docker-image: ${{ needs.pytorch-xla-linux-bionic-py3_7-clang8-build.outputs.docker-image }}
      test-matrix: |
        { include: [
          { config: "xla", shard: 1, num_shards: 1, runner: "linux.2xlarge" },

          { config: "xla", shard: 1, num_shards: 2, runner: "linux.2xlarge" },
          { config: "xla", shard: 2, num_shards: 2, runner: "linux.2xlarge" },

          { config: "xla", shard: 1, num_shards: 3, runner: "linux.2xlarge" },
          { config: "xla", shard: 2, num_shards: 3, runner: "linux.2xlarge" },
          { config: "xla", shard: 3, num_shards: 3, runner: "linux.2xlarge" },

          { config: "xla", shard: 1, num_shards: 4, runner: "linux.2xlarge" },
          { config: "xla", shard: 2, num_shards: 4, runner: "linux.2xlarge" },
          { config: "xla", shard: 3, num_shards: 4, runner: "linux.2xlarge" },
          { config: "xla", shard: 4, num_shards: 4, runner: "linux.2xlarge" },

          { config: "xla", shard: 1, num_shards: 5, runner: "linux.2xlarge" },
          { config: "xla", shard: 2, num_shards: 5, runner: "linux.2xlarge" },
          { config: "xla", shard: 3, num_shards: 5, runner: "linux.2xlarge" },
          { config: "xla", shard: 4, num_shards: 5, runner: "linux.2xlarge" },
          { config: "xla", shard: 5, num_shards: 5, runner: "linux.2xlarge" },
        ]}

  win-vs2019-cpu-py3-build:
    name: win-vs2019-cpu-py3
    uses: ./.github/workflows/_win-build.yml
    with:
      build-environment: win-vs2019-cpu-py3
      cuda-version: cpu

  win-vs2019-cpu-py3-test:
    name: win-vs2019-cpu-py3
    uses: ./.github/workflows/_win-test.yml
    needs: win-vs2019-cpu-py3-build
    with:
      build-environment: win-vs2019-cpu-py3
      cuda-version: cpu
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 1, runner: "windows.4xlarge" },

          { config: "default", shard: 1, num_shards: 2, runner: "windows.4xlarge" },
          { config: "default", shard: 2, num_shards: 2, runner: "windows.4xlarge" },

          { config: "default", shard: 1, num_shards: 3, runner: "windows.4xlarge" },
          { config: "default", shard: 2, num_shards: 3, runner: "windows.4xlarge" },
          { config: "default", shard: 3, num_shards: 3, runner: "windows.4xlarge" },

          { config: "default", shard: 1, num_shards: 4, runner: "windows.4xlarge" },
          { config: "default", shard: 2, num_shards: 4, runner: "windows.4xlarge" },
          { config: "default", shard: 3, num_shards: 4, runner: "windows.4xlarge" },
          { config: "default", shard: 4, num_shards: 4, runner: "windows.4xlarge" },

          { config: "default", shard: 1, num_shards: 5, runner: "windows.4xlarge" },
          { config: "default", shard: 2, num_shards: 5, runner: "windows.4xlarge" },
          { config: "default", shard: 3, num_shards: 5, runner: "windows.4xlarge" },
          { config: "default", shard: 4, num_shards: 5, runner: "windows.4xlarge" },
          { config: "default", shard: 5, num_shards: 5, runner: "windows.4xlarge" },
        ]}
